server:
  port: 3000

spring:
  main:
    web-application-type: servlet

springdoc.swagger-ui.path: ${SWAGGER_URL:/docs}
springdoc.default-produces-media-type: application/json
springdoc.default-consumes-media-type: application/json
