version: 0.2
phases:
  build:
    commands:
      - echo Java build started on `date`...
      - java -version
      - mvn -version
      - echo ...beginning packaging to jar...
      - mvn clean package deploy
      - echo ...Java build completed on `date`.

  post_build:
      commands:
      version: 0.0
      os: linux
      files:
        - source: /
          destination: /home/ec2-user/spring-boot-app
      hooks:
        ApplicationStart:
          - location: java -jar /home/ec2-user/spring-boot-app.jar
            timeout: 60
            runas: ec2-user
        AfterInstall:
          - location: |
              aws apigateway put-rest-api \
                --rest-api-id he6ttylibe \
                --mode merge \
                --body file://swagger/openapi.json \
                --region us-east-1
              aws apigateway create-deployment \
                --rest-api-id he6ttylibe \
                --stage-name dev \
                --region us-east-1
            timeout: 60
            runas: ec2-user

cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - '**/*'
