version: 0.2
env:
  variables:
    ECS_SERVICE_NAME: $ECS_SERVICE_NAME
    ENVIRONMENT:  $ENVIRONMENT
    OPENAPI_JSON_PATH: swagger/openapi.json
phases:
  build:
    commands:
      - apigateway-update.sh $ENVIRONMENT $ECS_SERVICE_NAME $OPENAPI_JSON_PATH
