version: 0.2
env:
  variables:
    ECS_SERVICE_NAME: $ECS_SERVICE_NAME
    ENVIRONMENT:  $ENVIRONMENT
    SWAGGER_BUCKET: $ENVIRONMENT-api-swagger
    BASE_URI: https://$ECS_SERVICE_NAME.$ENVIRONMENT.llzgarantidora.com
    OPENAPI_JSON_PATH: swagger/openapi.json
phases:
  build:
    commands:
      - apigateway-update.sh
